AllCops:
  TargetRubyVersion: 3.4
  NewCops: enable
  Exclude:
    - 'db/schema.rb'
    - 'vendor/**/*'
    - 'Attic/setup.rb'
    - 'origtest/**/*'

Style/StringLiterals:
  Enabled: false

# DISABLED
Lint/ShadowedArgument:                  { Enabled: false }
Lint/UnusedBlockArgument:               { Enabled: false }
Lint/MissingSuper:                      { Enabled: false }
Lint/ElseLayout:                        { Enabled: false }
Lint/DuplicateRequire:                  { Enabled: false }

# NOT DANGEROUS
Lint/UselessAssignment:                 { Enabled: false }
Lint/UnusedMethodArgument:              { Enabled: false }
Lint/UnderscorePrefixedVariableName:    { Enabled: false }
Lint/Void:                              { Enabled: false }
Lint/UselessMethodDefinition:           { Enabled: false }
Lint/RedundantStringCoercion:           { Enabled: false }

# FIXED
#Lint/AmbiguousRegexpLiteral:            { Enabled: false }
#Lint/AssignmentInCondition:             { Enabled: false }
#Lint/DuplicateMethods:                  { Enabled: false }
